# Basic
title: Akatsuki
subtitle: akatsukis.me
welcome_message: ❤<a href="http://changeless.me" target="_blank">changeless</a>
description: ACMer/Arch Linux user/头像是本人
creator: <a href="https://github.com/Akatsukis">@Akatsuki</a>

url: "http://akatsukis.me"

author:
  name: 'Akatsuki'

permalink: /:year/:month/:title/

# Format
markdown: kramdown
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: akatsukis
    # duoshuo: 
    
# Social
#social:
#    weibo: onevcat
#    github: onevcat
#    twitter: onevcat
#    gplus: 107108267983477358170
#    mail: onev@onevcat.com

# Google Analytics
#ga:
    # id: your_ga_id
    # host: your_host
